services:
    mazeltof.proflatvariations.listener:
        class: mazeltof\proflatvariations\event\listener
        arguments:
            - '@user'
            - '@template'
        tags:
            - { name: event.listener }
